services:

  otel-collector:
    image: otel/opentelemetry-collector:0.120.0
    container_name: otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./telemetry-data.json:/etc/telemetry-data.json
    networks:   
      - demonet   
    ports:
      - "4318:4318"

networks:
  demonet:
    driver: bridge
    external: true
    name: demonet
    # Ensure the network 'demonet' exists before running this service
    # You can create it with:
    # docker network create demonet
    # If you want to use a different network, change the name here and in the docker-compose.yml file
    # Ensure the network is created before running this service


